### ISSUE TITLE
Try to stringify `@actual` during comparison

### ISSUE THREAD

**Issue by jreut** [yesmeck/rspec-snapshot#2]
First off, thanks for writing this helpful library!

I noticed a small inconvenience when trying to snapshot Ruby data structures. For instance, this example fails

```ruby
RSpec.describe 'snapshots of simple data structures' do
  subject { %w(a simple list) }
  it { should match_snapshot('my_list') }
end
```

with a confusing message:

```
 Failure/Error: it { should match_snapshot('my_list') }

       expected: ["a", "simple", "list"]
            got: ["a", "simple", "list"]
```

At first glance, the expected and actual values look identical, but that's because [`#failure_message`][failure_message] stringifies both values.

Since this matcher implicitly stringifies on the way out (via the call to [`File#write`][file-write]), what do you think about changing the [comparison line][comparison-line] from `@actual == @expect` to something along the lines of `@actual.to_s == @expect`? I'm happy to write a pull request with associated tests.

[failure_message]: https://github.com/yesmeck/rspec-snapshot/blob/9a12c50f17067b86f4e8c9750641e65f07f4efa4/lib/rspec/snapshot/matchers/match_snapshot.rb#L32-L34
[file-write]: https://github.com/yesmeck/rspec-snapshot/blob/9a12c50f17067b86f4e8c9750641e65f07f4efa4/lib/rspec/snapshot/matchers/match_snapshot.rb#L25
[comparison-line]: https://github.com/yesmeck/rspec-snapshot/blob/9a12c50f17067b86f4e8c9750641e65f07f4efa4/lib/rspec/snapshot/matchers/match_snapshot.rb#L21

**Comment by jreut** [comment]
I should mention this issue is easily resolved by changing the spec subject from `%w(a simple list)` to `%w(a simple list).to_s`, but I think adding stringification to the library will help to expand its utility beyond simple string matching. Looking further, it may even be reasonable to support configurable (de)serialization for arbitrarily complex data structures.

**Comment by yesmeck** [comment]
@jreut Adding stringification is make sense, feel free to open a PR.

For more complex data structures, I'd like to a config to allow people specify a custom serializer to serialize the data.
```ruby
RSpec.configure do |config|
  config.serializer = CustomSerializer
end
```

**Comment by jreut** [comment]
I agree it would be nice to have configurable serialization. I opened #3 to cover naïve stringification, and I would be happy to write another PR that is more configurable. To that effect, have you ever heard of [`Marshal`][doc-marshal]? It is a module in Ruby core that provides easy serialization (although it is not very human-readable). `Marshal` is also quite configurable. You only need to define two instance methods, `#marshal_dump` and `#marshal_load` on each class that needs special serialization. I imagine an API something like these snippets:

```ruby
# /lib/rspec/snapshot/matchers.rb
def match_snapshot(snapshot_name, strategy: DefaultSerializer)
  MatchSnapShot.new(self.class.metadata, snapshot_name, strategy)
end
```

```ruby
# /lib/rspec/snapshot/matchers/match_snapshot.rb

class MatchSnapshot
  def initialize(metadata, snapshot_name, strategy)
    @strategy = strategy
  end

  def matches?(actual)
    refine_class! @actual.class
    # when creating the snapshot:
    snapshot_file.write Marshal.dump @actual
    # when reading the snapshot
    @expected = Marshal.load snapshot_file.read
  end

  private

  def refine_class!(klass)
    klass.refine { include @strategy }
  end
end
```

```ruby
# /lib/rspec/snapshot/serializers/default_serializer.rb
module RSpec
  module Snapshot
    module Serializers
      module DefaultSerializer
        # use the default `Marshal.load`/`Marshal.dump` behavior
        def marshal_load; end
        def marshal_dump; end
      end
    end
  end
end
```

I have not yet worked out the details, but how does this seem as a plan?

[doc-marshal]: http://ruby-doc.org/core-2.4.0/Marshal.html

**Comment by yesmeck** [comment]
Since Marshal's dump result is not human friendly, I think the DefaultSerializer can keep using `to_s`。

I prefer to chose `load` and `dump` for  the serializer's API.

Beside the DefaultSerializer, we can create some other serializers, like HTMLSerializer which can beautify HTML(#1), JSONSerializer which can format JSON .

**Comment by yesmeck** [comment]
Oh, a Serializer only need a `dump` API.

**Comment by jreut** [comment]
Ah, you're right! I'll start to work on a PR.
